In [1]:
import sys
sys.path.append("../src")
from functions import *
import pandas as pd

In [12]:
year = 2023
selected_columns = ["Div", "Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", 
                    "FTR", "HTHG", "HTAG", "HTR", "Referee", "HS", "AS", 
                    "HST", "AST", "HF", "AF", "HC", "AC", "HY", "AY", "HR", "AR"]
dfs = []

while year > 2009:
    temp = read_csv(f'premier_{year}')
    temp = temp[selected_columns]
    dfs.append(temp)
    year -= 1

df_premier = pd.concat(dfs, ignore_index=True)

In [14]:
years = [2020, 2021, 2022] 
class_table = create_classification_table(df_premier, years)
class_table

,Team,Total Points,Wins,Draws,Loses,Goals Diff,Goals For,Goals Against
13,Man City,255.0,80.0,15,15.0,188.0,274.0,86.0
12,Liverpool,233.0,70.0,23,18.0,127.0,233.0,106.0
0,Arsenal,205.0,63.0,16,31.0,67.0,186.0,119.0
14,Man United,199.0,57.0,28,25.0,54.0,188.0,134.0
6,Chelsea,196.0,56.0,28,25.0,75.0,187.0,112.0
20,Tottenham,192.0,57.0,21,32.0,69.0,195.0,126.0
23,West Ham,155.0,44.0,23,45.0,13.0,163.0,150.0
11,Leicester,155.0,44.0,23,44.0,19.0,180.0,161.0
15,Newcastle,147.0,38.0,33,40.0,-23.0,140.0,163.0
24,Wolves,138.0,38.0,24,49.0,-30.0,106.0,136.0
8,Everton,137.0,37.0,26,48.0,-36.0,124.0,160.0
1,Aston Villa,135.0,38.0,21,51.0,-16.0,140.0,156.0
4,Brighton,134.0,31.0,41,38.0,-15.0,125.0,140.0
7,Crystal Palace,130.0,33.0,31,46.0,-40.0,121.0,161.0
19,Southampton,125.0,33.0,26,52.0,-57.0,132.0,189.0
10,Leeds,113.0,31.0,20,41.0,-35.0,127.0,162.0
5,Burnley,104.0,25.0,29,40.0,-39.0,87.0,126.0
3,Brentford,69.0,18.0,15,22.0,-8.0,75.0,83.0
9,Fulham,53.0,12.0,17,26.0,-24.0,56.0,80.0
18,Sheffield United,48.0,14.0,6,36.0,-47.0,36.0,83.0
21,Watford,41.0,11.0,8,37.0,-53.0,55.0,108.0
2,Bournemouth,30.0,8.0,6,21.0,-35.0,38.0,73.0
16,Norwich,30.0,7.0,9,40.0,-91.0,28.0,119.0
22,West Brom,26.0,5.0,11,22.0,-41.0,35.0,76.0
17,Nott'm Forest,13.0,3.0,4,9.0,-22.0,11.0,33.0