In [2]:
import sys
sys.path.append("../src")
from functions import *
import pandas as pd

In [3]:
year = 2023
selected_columns = ["Div", "Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", 
                    "FTR", "HTHG", "HTAG", "HTR", "Referee", "HS", "AS", 
                    "HST", "AST", "HF", "AF", "HC", "AC", "HY", "AY", "HR", "AR"]
dfs = []

while year > 2009:
    temp = read_csv(f'premier_{year}')
    temp = temp[selected_columns]
    dfs.append(temp)
    year -= 1

df_premier = pd.concat(dfs, ignore_index=True)
df_premier = add_year(df_premier, 'Date')
df_premier = calculate_points(df_premier)
df_premier

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HC,AC,HY,AY,HR,AR,Year,home_team_points,away_team_points
0,E0,2023-08-11,Burnley,Man City,0.0,3.0,A,0.0,2.0,A,...,8.0,6.0,5.0,0.0,0.0,1.0,0.0,2023.0,0,3
1,E0,2023-08-12,Arsenal,Nott'm Forest,2.0,1.0,H,2.0,0.0,H,...,12.0,8.0,3.0,2.0,2.0,0.0,0.0,2023.0,3,0
2,E0,2023-08-12,Bournemouth,West Ham,1.0,1.0,D,0.0,0.0,D,...,14.0,10.0,4.0,1.0,4.0,0.0,0.0,2023.0,1,1
3,E0,2023-08-12,Brighton,Luton,4.0,1.0,H,1.0,0.0,H,...,12.0,6.0,7.0,2.0,2.0,0.0,0.0,2023.0,3,0
4,E0,2023-08-12,Everton,Fulham,0.0,1.0,A,0.0,0.0,D,...,6.0,10.0,4.0,0.0,2.0,0.0,0.0,2023.0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5316,E0,2011-05-22,Newcastle,West Brom,3.0,3.0,D,2.0,0.0,H,...,8.0,7.0,6.0,0.0,0.0,0.0,0.0,2011.0,1,1
5317,E0,2011-05-22,Stoke,Wigan,0.0,1.0,A,0.0,0.0,D,...,9.0,5.0,3.0,1.0,4.0,0.0,0.0,2011.0,0,3
5318,E0,2011-05-22,Tottenham,Birmingham,2.0,1.0,H,0.0,0.0,D,...,15.0,7.0,5.0,0.0,3.0,0.0,0.0,2011.0,3,0
5319,E0,2011-05-22,West Ham,Sunderland,0.0,3.0,A,0.0,1.0,A,...,8.0,4.0,6.0,0.0,2.0,0.0,0.0,2011.0,0,3
5320,E0,2011-05-22,Wolves,Blackburn,2.0,3.0,A,0.0,3.0,A,...,9.0,8.0,3.0,3.0,1.0,0.0,0.0,2011.0,0,3